name: book
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - fastcache=1.1.0=py37h0b31af3_0
  - freetype=2.10.0=h24853df_1
  - gmp=6.1.2=h0a44026_1000
  - gmpy2=2.1.0b1=py37h4160ff4_0
  - importlib_metadata=1.4.0=py37_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_1
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37ha1b3eb9_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.1=1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h3d69b6c_7
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.17=h01d97ff_0
  - llvm-openmp=9.0.1=h28b9765_1
  - markupsafe=1.1.1=py37h0b31af3_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h11da6c2_1
  - mistune=0.8.4=py37h0b31af3_1000
  - more-itertools=8.1.0=py_0
  - mpc=1.1.0=h4160ff4_1006
  - mpfr=4.0.2=h44b798e_0
  - mpmath=1.1.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - ncurses=6.1=h0a44026_1002
  - notebook=6.0.1=py37_0
  - numpy=1.17.3=py37hde6bac1_0
  - openssl=1.1.1d=h0b31af3_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.15.7=py37h0b31af3_0
  - python=3.7.6=h5c2c468_2
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py37h4bf09a9_0
  - readline=8.0=hcfe32e1_0
  - send2trash=1.5.0=py_0
  - setuptools=45.0.0=py37_1
  - six=1.14.0=py37_0
  - sqlite=3.30.1=h93121df_0
  - sympy=1.5.1=py37_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.3=py37h0b31af3_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=1.0.0=py_0
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/john/miniconda3/envs/book

